import { artifacts } from "hardhat";
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Writes the compiled ABIs into the web app as `as const` TypeScript so viem
 * and wagmi can type every call. Run after any change to the contracts:
 *
 *   npm run compile && npm run export-abi
 */
async function main() {
  const outDir = join(__dirname, "..", "..", "src", "lib", "abi");
  mkdirSync(outDir, { recursive: true });

  for (const [name, exportName] of [
    ["ClipEscrow", "clipEscrowAbi"],
    ["ClipToken", "clipTokenAbi"],
  ] as const) {
    const artifact = await artifacts.readArtifact(name);
    const body =
      `// Generated by contracts/scripts/export-abi.ts from ${name}.sol — do not edit.\n` +
      `export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
    writeFileSync(join(outDir, `${name}.ts`), body);
    console.log(`wrote src/lib/abi/${name}.ts`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
